[workspace]

members = [
    "day1-rs",
    "day1part2-rs",
    "day2-rs",
    "day2part2-rs",
    "day3-rs",
    "day4part2-rs",
    "readerr",
]

[workspace.dependencies]
anyhow = "1.0.79"
readerr= { path = "./readerr" }
